### ISSUE TITLE
Export to .obj

### ISSUE THREAD

**Issue by widmowyfox** [hexabits/nifskope#11]
Hi, why export to .obj creates only empty .obj and .mtl files? No data, just blank file. Model in nifscope looks fine.

Model in nifskope https://s13.postimg.org/oy37afjtj/nifnozap.jpg

**Comment by hexabits** [comment]
Because export hasn't been updated for SSE skinned meshes.  Material files will always be blank or useless though.  Not sure they were ever updated for BSShaderTextureSet.

**Comment by Seneral** [comment]
Any chance getting export to work? Have tried through workarounds but as Nifskope 1 is unable to open the new files I see no way of exporting objects out of SSE...

**Comment by Bronzeborg** [comment]
so. they are just leaving nifskope like this? not being able to export sse files? lol
