### ISSUE TITLE
missing dll files in nifskope 2 dev 6

### ISSUE THREAD

**Issue by texastim** [hexabits/nifskope#13]
missing QT5Network.dll, Opengl.dll , Widgets.dll , XML,dll .
will not Run
W10 64
download dev5 , it works and has the dll files included in the Zip file. but i think i need 6. 
want to learn to mod skyrim.
texastimlubbock50@gmail.com

**Comment by neomonkeus** [comment]
Verified both downloads in the download section contain the above dlls.
Which link did you use?

**Comment by hexabits** [comment]
Closing this as we know that the official downloads have the correct DLLs and have not received any kind of response.
