### ISSUE TITLE
Error during shader compilation on start

### ISSUE THREAD

**Issue by Morghean** [hexabits/nifskope#16]
Hi!
2.0 (alpha 6)
I get this message every time a new nifskope window starts:

fo4_default.vert:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 0:3: 'out' : syntax error parse error
ERROR: 2 compilation errors.  No code generated.

fo4_effectshader.vert:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 0:3: 'out' : syntax error parse error
ERROR: 2 compilation errors.  No code generated.

fo4_env.vert:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 0:3: 'out' : syntax error parse error
ERROR: 2 compilation errors.  No code generated.

ob_glowmap.vert:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 1 compilation errors.  No code generated.

ob_material_default.vert:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 1 compilation errors.  No code generated.

ob_vcolors_ad.vert:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 1 compilation errors.  No code generated.

ob_vcolors_e.vert:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 1 compilation errors.  No code generated.

sk_default.vert:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 1 compilation errors.  No code generated.

sk_effectshader.vert:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 1 compilation errors.  No code generated.

sk_env.vert:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 1 compilation errors.  No code generated.

sk_glowmap.vert:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 1 compilation errors.  No code generated.

sk_msn.vert:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 1 compilation errors.  No code generated.

sk_multilayer.vert:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 1 compilation errors.  No code generated.

fo4_default.frag:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 0:43: 'in' : syntax error parse error
ERROR: 2 compilation errors.  No code generated.

fo4_effectshader.frag:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 0:40: 'in' : syntax error parse error
ERROR: 2 compilation errors.  No code generated.

fo4_env.frag:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 0:2: '' :  extension 'GL_ARB_shader_texture_lod' is not supported
ERROR: 0:46: 'in' : syntax error parse error
ERROR: 3 compilation errors.  No code generated.

ob_normalglowmap.frag:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 0:63: 'f' : syntax error parse error
ERROR: 2 compilation errors.  No code generated.

ob_normalmap.frag:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 0:81: 'f' : syntax error parse error
ERROR: 2 compilation errors.  No code generated.

ob_parallax.frag:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 1 compilation errors.  No code generated.

ob_parallaxglowmap.frag:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 1 compilation errors.  No code generated.

sk_default.frag:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 1 compilation errors.  No code generated.

sk_effectshader.frag:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 1 compilation errors.  No code generated.

sk_env.frag:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 1 compilation errors.  No code generated.

sk_glowmap.frag:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 1 compilation errors.  No code generated.

sk_msn.frag:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 1 compilation errors.  No code generated.

sk_multilayer.frag:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 1 compilation errors.  No code generated.

sk_parallax.frag:

ERROR: 0:1: '' :  Version number not supported by GL2
ERROR: 1 compilation errors.  No code generated.

fo4_default.prog:

depends on shader fo4_default.vert which was not compiled successful
fo4_effectshader.prog:

depends on shader fo4_effectshader.vert which was not compiled successful
fo4_env.prog:

depends on shader fo4_env.vert which was not compiled successful
ob_normal+glowmap.prog:

depends on shader ob_glowmap.vert which was not compiled successful
ob_normal+glowmap_vcol.prog:

depends on shader ob_glowmap.vert which was not compiled successful
ob_normalmap.prog:

depends on shader ob_material_default.vert which was not compiled successful
ob_normalmap_vcol_ad.prog:

depends on shader ob_vcolors_ad.vert which was not compiled successful
ob_normalmap_vcol_e.prog:

depends on shader ob_vcolors_e.vert which was not compiled successful
ob_parallax+glowmap.prog:

depends on shader ob_glowmap.vert which was not compiled successful
ob_parallax.prog:

depends on shader ob_material_default.vert which was not compiled successful
ob_parallax_vcol_ad.prog:

depends on shader ob_vcolors_ad.vert which was not compiled successful
ob_parallax_vcol_e.prog:

depends on shader ob_vcolors_e.vert which was not compiled successful
sk_default.prog:

depends on shader sk_default.vert which was not compiled successful
sk_effectshader.prog:

depends on shader sk_effectshader.vert which was not compiled successful
sk_env.prog:

depends on shader sk_env.vert which was not compiled successful
sk_glowmap.prog:

depends on shader sk_glowmap.vert which was not compiled successful
sk_msn.prog:

depends on shader sk_msn.vert which was not compiled successful
sk_multilayer.prog:

depends on shader sk_multilayer.vert which was not compiled successful
sk_parallax.prog:

depends on shader sk_default.vert which was not compiled successful

dunno what it is though.. thought I'd share it..

**Comment by ousnius** [comment]
Did you install and overwrite all files that come with the latest release archive? Are your graphics drivers up to date for all chips if you have multiple?

**Comment by hexabits** [comment]
@Morghean  Please leave better tickets.  You didn't even mention your GPU model and what drivers you have.  

My shaders are valid GLSL as I have validated all of them with glslLangValidator, so it would seem you are a victim of either very poor GL support or inordinately strict GL support from your drivers.

Completely delete your NifSkope folder and reinstall, if it persists, just disable Shaders in the properties or delete the shaders folder in the NifSkope directory.  There is nothing else to be done regarding this as it's not a bug so I will close the ticket.
