### ISSUE TITLE
Unable to add custom resource paths.

### ISSUE THREAD

**Issue by Morghean** [hexabits/nifskope#17]
As the title says. When trying to add a new folder, the window won't take a folder for an answer, only a file could be opened with this, so I can't set up custom paths.

**Comment by kkthebeast** [comment]
Try renaming your nifskope folder to something else, then do a fresh install. see if it does it on the new install too. Also if that doesn't work try running Nifskope as Admin. last resort try version alpha 5 for good measure, save often as Jon fixed a memory leak from 5 to 6. 5 has never crashed for me though.

**Comment by kingtobbe** [comment]
Sounds odd, are you sure you are in the path tab not the archives tab? 
![image](https://cloud.githubusercontent.com/assets/19521230/24833298/023423f4-1cc5-11e7-8858-96dfd70b4a71.png)

**Comment by hexabits** [comment]
In addition to what has already been said, the "Add Folder" button just opens up a standard Windows dialog and there is nothing I can actually do about that if it's not letting you choose a folder.  It is set up to allow folder selection, and it works fine for everybody else.  It seems then you might have some kind of platform issue. 

Definitely follow the clean install method suggested as old DLLs hanging around is a known source of random bugs.

**Comment by hexabits** [comment]
Closing since there is a new Game Manager
