### ISSUE TITLE
Texture doesn't appear in UV editor

### ISSUE THREAD

**Issue by narg999** [hexabits/nifskope#18]
Resource paths are set and textures are used for rendering, but don't appear in the UV editor. (Alpha 6, FO4 nif, non-vanilla tex)

**Comment by josephcrowell** [comment]
BC7 compressed textures aren't supported yet.

**Comment by hexabits** [comment]
@meliodasx  Yes, but that's not the reason for this issue.  I will eventually support BC7. 

Since he opened this on the other repo,  [the other ticket](https://github.com/niftools/nifskope/issues/105) will be used instead.
