### ISSUE TITLE
Save as...

### ISSUE THREAD

**Issue by li-marigold** [hexabits/nifskope#27]
Why save as menu not workin'?

**Comment by yarrmateys** [comment]
it only doesn't work for fo76 format, which probably isn't fully understood yet. with fo76 not being moddable it's understandable, it's harder to do proper testing with a game that doesn't want to be modded and even threatens the modders with bans. it works for me in other game modes. if all you want is the fo76 meshes you can just export them to obj.

it's actually possible to save it if you just close the program and say yes when it asks to save, but as i thought it just generates a broken file that can't be read.

**Comment by li-marigold** [comment]
> it only doesn't work for fo76 format, which probably isn't fully understood yet. with fo76 not being moddable it's understandable, it's harder to do proper testing with a game that doesn't want to be modded and even threatens the modders with bans. it works for me in other game modes. if all you want is the fo76 meshes you can just export them to obj.
> 
> it's actually possible to save it if you just close the program and say yes when it asks to save, but as i thought it just generates a broken file that can't be read.

uh....I see. Thanks!. I've exported some meshes to obj already and rigged in max 2016

**Comment by hexabits** [comment]
Saving NIFs is not supported because mods are not supported.
