### ISSUE TITLE
Can't get textures to show up for Morrowind meshes in Dev 8

### ISSUE THREAD

**Issue by PhiMue86** [hexabits/nifskope#30]
Works in Dev 7, but no matter what I do, textures are not displayed. I also tried some Fallout 3 meshes, which appeared to be working, but only with loose files, not with archives, it seems.

**Comment by jimbot70** [comment]
Similar issue for Oblivion for me. 

I can get it to display a texture if I manually fill the file path to be the full path but it won't automatically use the correct texture like it used to even with the correct paths and archives added in the settings.

**Comment by hexabits** [comment]
I know I ignored this for a while but I finally looked into the issue.  

For Oblivion, between Steam, GOG, and the original disc version, the NIFs vary wildly in their version info and for some distributions of the game the detection was failing.  They were being detected as Fallout 3 and in the meantime one can add the Oblivion archives to the Fallout 3 section. 

For Morrowind, this was simply an oversight.  In the meantime, one can enable Other Games in the Games tab, then add the Morrowind archives under Other Games. 

I'll release a build with a fix shortly.

**Comment by PhiMue86** [comment]
Works now!

**Comment by Darklocq** [comment]
Off-topic, but I have to say I'm so glad to see someone who knows what they're doing is still keeping this tool alive!  I had thought it was stuck forever at 2.0 Dev 7, from 2017.  Glad I saw the "also forked to jonwd7/nifskope" notice.

More on-topic, it's good to see the sort of work-around mentioned above. I probably never would've thought of that.  While I'm wallowing in Skyrim right now, I do venture back into the earlier games and would surely have tried tweaking NIFs in them at some point.
