### ISSUE TITLE
Crash after deleting blocks

### ISSUE THREAD

**Issue by Psycho-Bill** [hexabits/nifskope#34]
mostly after the 3rd block i delete, NifSkope 2.0 Dev7 crashes, then after 2 deletes then after 1 and then back to 3 LOL
Windows10, tried fresh install.

**Comment by hexabits** [comment]
Can't really do anything without an example.  This is not general behavior.  Also, update your version.  There's a dev8.

**Comment by Psycho-Bill** [comment]
where is this dev8 at? all i can find is 7

**Comment by Psycho-Bill** [comment]
nevermind, Hana showed me. will see if problem still happens and report
