### ISSUE TITLE
Dev 9, BSTriShape mesh normals preview is wrong and "Update Tangent Space" throws warnings on BSTriShapes

### ISSUE THREAD

**Issue by ja231c** [hexabits/nifskope#54]
Happens with all BSTriShapes, be it Fallout 4, Skyrim SE or Fallout 76
Possibly a nif.xml problem, it works fine with the one from Dev 8.

**Comment by ja231c** [comment]
Although now that I look at the latest commits it might be already fixed.

**Comment by hexabits** [comment]
Indeed. I will close this when I update the release.  I have an issue with facegen meshes and glTF I want to try to address first though.

**Comment by hexabits** [comment]
@ja231c  can you confirm to me the updated dev9 release is fine with these issues?

**Comment by ja231c** [comment]
Yes, I can confirm that it is in fact fixed in Dev 9 from 2023-09-29
