### ISSUE TITLE
[Dev 9] Textures from other game folders not loading

### ISSUE THREAD

**Issue by GammaMetroid** [hexabits/nifskope#58]
In a Skyrim LE nif, I have texture paths pointing to loose textures in my SSE\Data\textures folder, but Nifskope acts as if it can't find them (shows as solid pink). I am unsure if this behavior is intended, but I do have the "Search other games if no match" box ticked.

**Comment by hexabits** [comment]
@GammaMetroid  If you have them listed under Skyrim SE and not Skyrim LE then this is intended.   The point of the game manager was to keep NIFs from improperly searching other games' archives/paths.  If you want this behavior, add the SSE dirs to the Skyrim (not Skyrim SE) section.

**Comment by GammaMetroid** [comment]
Ohhh, that makes sense. Thanks!

**Comment by hexabits** [comment]
@GammaMetroid I'm assuming you have no issues now and I can close this but let me know.
