### ISSUE TITLE
[dev 9] Broken display of compressed mesh shape collision

### ISSUE THREAD

**Issue by GammaMetroid** [hexabits/nifskope#66]
Compressed mesh shape collision appears to have some vertices out of place. The more complex the shape, the more obvious the errors. Primitives and convex shapes look okay. Here is a vanilla Skyrim nif for example:
![highhrothgar](https://github.com/hexabits/nifskope/assets/101038501/12a1ffe7-f702-45ce-9a81-a32ea0256620)

**Comment by hexabits** [comment]
![image](https://github.com/hexabits/nifskope/assets/170077/28d902ea-f971-4ab5-9552-2ba3ccb9802b)

This was fixed,  you probably haven't upgraded.

**Comment by hexabits** [comment]
@GammaMetroid  In case you're confused, the dev9 release link gets continual updates, so that the link remains stable for people linking to it.  The changelog and zip files are dated however.
