### ISSUE TITLE
Unable to open SSE Argonian and Khajiit tails

### ISSUE THREAD

**Issue by VectorPlexus** [hexabits/nifskope#7]
As the title describes, Nifskope gives the following details error msg: failed to load file footer

As a side note, when trying to open it on the old Nifskope, its still able to load the dummy bones, but doesnt load the mesh. Also, apparently the NiTriShape node has the name of BSTriShape instead:

""warning: block 9 (BSTriShape) not inserted!"" 
""device position incorrect after block number 9 (BSTriShape) at 0x4db ended at 0x4db (expected 0x553)"" 
""device position incorrect after block number 10 (BSDismemberSkinInstance) at 0x553 ended at 0x583 (expected 0x587)"" 
""array Roots much too large. 1065353216 bytes requested"" 
""device position incorrect after block number 11 (NiSkinData) at 0x587 ended at 0x58b (expected 0x1272)"" 
""device position incorrect after block number 12 (NiSkinPartition) at 0x1272 ended at 0x127a (expected 0x4ec4)"" 
""device position incorrect after block number 13 (BSLightingShaderProperty) at 0x4ec4 ended at 0x4edc (expected 0x4f34)"" 
""device position incorrect after block number 14 (BSShaderTextureSet) at 0x4f34 ended at 0x4f5c (expected 0x5028)""

**Comment by ousnius** [comment]
The NiTriShape block was swapped out by the new BSTriShape block for the vanilla SSE meshes, the old NifSkope obviously can't open that.

However, I can open all Argonian and Khajiit tails just fine. Are you using the pre-alpha 6 already?

**Comment by VectorPlexus** [comment]
I was using:
Nifskope 2.0.dev4 (revision 584126c) Nifskope 2.0.0 Pre-Alpha 4, downloaded it today, but apparently DLed an older version (from 2015-12-14). I downloaded the last one and its working perfectly, sorry for bugging you =)
