### ISSUE TITLE
Failed to load NIF file.

### ISSUE THREAD

**Issue by Velken** [hexabits/nifskope#8]
Whenever I try to load a .nif file I get failed to load and the following warnings:
device position incorrect after block number 5 (bhkRigidBodyT) at 0x46a ended at 0x4910 (expected 0x564)
device position incorrect after block number 6 (bhkCollisionObject) at 0x564 ended at 0x568 (expected 0x56e)
device position incorrect after block number 7 (BSTriShape) at 0x56e ended at 0x572 (expected 0x4836)
device position incorrect after block number 8 (BSLightingShaderProperty) at 0x4836 ended at 0x483a (expected 0x489a)
device position incorrect after block number 9 (BSShaderTextureSet) at 0x489a ended at 0x489e (expected 0x4908)

**Comment by hexabits** [comment]
@Velken 

You know, it'd really help if you actually said what game the NIF was for and what version of NifSkope you were using.  Otherwise your bug report means nothing.  I can't do anything with the information you provided.

**Comment by Velken** [comment]
Sorry, I forgot, it was 3 AM when I posted the bug report.
NifSkope_2_0_2016-04-11-1
Skyrim Special Edition

**Comment by hexabits** [comment]
As it seems you figured out, you were using a 6.5 month old version to open brand new NIFs.

**Comment by Velken** [comment]
Well, where can I download the new one? I've only found one download place and is not sourceforge (as you can see in this screenshot, there is no files there: http://prntscr.com/d3yjap )
