### ISSUE TITLE
Support of Davilex games

### ISSUE THREAD

**Issue by 6n4mpf** [hexabits/nifskope#84]
Hey guys,

the Davilex games Autobahn Raser IV, Alarm for Cobra 11: Hot Pursuit and so on are also using .nif format for graphics and 3d models. Is there a possibility to add support for these games? I tried to open the files with nifskope and it seems the files get loaded without errors, but nothing shows up in the 3d view, only some particular informations in the info windows. It seems only the Skyboxes are working well, but they show some errors.

**Comment by johnsone006** [comment]
Hey, so I am not a nifSkope dev, but I have used NifSkope often and I have a suspicion about what's going on here.
When nothing shows up in the object viewer, have you tried using the controls that are used to change the view to check if the default view simply just doesn't show the mesh? It's a common problem to experience with certain Skyrim se meshes. Look for controls directly above the viewport that are labeled Top, front, left, flip, or perspective. To see the labels, simply hover the mouse over a control for a few seconds.

**Comment by 6n4mpf** [comment]
Thanks for your reply. Seems like I'm wrong. Some 3d models show up, I think the .nif files who don't show up just contain some graphic informations instead of a 3d model with textures and can't be shown.

**Comment by 6n4mpf** [comment]
Thanks for your reply. Seems like I'm wrong. Some 3d models show up, I think the .nif files who don't show up just contain some graphic informations instead of a 3d model with textures and can't be shown.

**Comment by johnsone006** [comment]
> Thanks for your reply. Seems like I'm wrong. Some 3d models show up, I think the .nif files who don't show up just contain some graphic informations instead of a 3d model with textures and can't be shown.
No no. .nif files are 3d object files. Not graphics. The graphics aspect is a separate file format, usually .dds. But certainly, you can let this go if you'd like, I just wanted to clarify .

**Comment by johnsone006** [comment]
Thats not what I meant at all. .nif files are 3d object files, not graphics. the graphics is a separate file type, usually .dds.
Let me clarify further.
When professional 3d artists realize that parts of their meshes won't be seen in game, its common for them to not to bother applying textures to those parts to save time and money. So what I think is happening here is that NifSkope is loading the parts of the mesh that the original artist anticipated wouldn't be visible to the camera as part of the default view. So, if you adjust the view, you might see the graphics of the mesh show up.
